# Generated by Django 4.0.4 on 2022-04-16 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '유저목록'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
