# Generated by Django 4.0.4 on 2022-04-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('description', models.CharField(max_length=200, verbose_name='상품설명')),
                ('once_funding', models.IntegerField(verbose_name='1회펀딩금액')),
                ('total_funding', models.IntegerField(default=0, verbose_name='현재펀딩금액')),
                ('goal_price', models.IntegerField(verbose_name='목표펀딩금액')),
                ('goal_percent', models.IntegerField(default=0, verbose_name='달성률')),
                ('today', models.DateField(auto_now=True, verbose_name='오늘날짜')),
                ('end_day', models.DateField(verbose_name='종료날짜')),
                ('created_at', models.DateField(auto_now=True, verbose_name='생성일')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name_plural': '상품목록',
                'db_table': 'products',
            },
        ),
    ]
