# Generated by Django 4.0.4 on 2022-04-19 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_products_applicants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='applicants',
            field=models.ManyToManyField(default={}, related_name='product_applicants', to=settings.AUTH_USER_MODEL),
        ),
    ]
